apiVersion: apps/v1
kind: Deployment
metadata:
  name: konw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: konw
  template:
    metadata:
      labels:
        app: konw
    spec:
      containers:
      - image: okteto.dev/konw:latest
        name: konw
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "27b52fc9-9f16-4566-ba1d-af5d07e6dd52 "
        - name: Vless_Path
          value: "/vl5d55"
        - name: Vmess_UUID
          value: "27b52fc9-9f16-4566-ba1d-af5d07e6dd52 "
        - name: Vmess_Path
          value: "/vm6b66"
        - name: Share_Path
          value: "/v2link"
